### ISSUE TITLE
【菁英计划验收】运行evaluate文件报错

### ISSUE THREAD

**Issue by shiyutang** [pooruss/ICNet-paddle#1]
同学你好，下载模型后，进行评估时发生报错：

![image](https://user-images.githubusercontent.com/34859558/139813485-33b9fdb9-1859-4075-be62-b4365fbdcb98.png)

**Comment by shiyutang** [comment]
同时运行train.py报错
![image](https://user-images.githubusercontent.com/34859558/139813965-2efd77e9-3336-467d-8ca0-530675a3534a.png)

**Comment by pooruss** [comment]
抱歉老师，部分代码文件没更新，现应已解决

**Comment by shiyutang** [comment]
更新代码后运行报错
![image](https://user-images.githubusercontent.com/34859558/139821925-14b2af8e-c309-4a19-8f11-0593eff9ed16.png)

**Comment by shiyutang** [comment]
更新代码后训练报错：
![image](https://user-images.githubusercontent.com/34859558/139825612-6236f5cf-2b65-447f-87bb-646fc8aeb444.png)

**Comment by pooruss** [comment]
抱歉老师，代码已排查完毕！（paddle版本2.2.0rc）
